version: "3"

services:

  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    restart: always
    ports:
    - "3000:3000"

  backend:
    container_name: backend
    build: backend/
    image: backend
    restart: always
    ports:
    - "5000:80"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - database/docker.env
#    networks:
#    - postgres

#	pgadmin:
#		links:
#		- postgres:postgres
#		container_name: pgadmin
#		image

#networks:
#  postgres:
#    driver: bridge
