version: "3"

services:

  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    restart: always
    ports:
    - "3000:3000"

  backend:
    container_name: backend
    build: backend/
    image: backend
    restart: always
    ports:
    - "5000:80"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - database/docker.env

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    links: 
    - postgres:db
    ports:
    - "8080:8080"

  jest:
    container_name: jest
    build: jest/
    image: jest

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4:latest
#    env_file:
#    - database/docker.env
#    ports:
#    - "8080:80"
#    volumes:
#    - /data/pgadmin:/root/.pgadmin

#networks:
#  postgres:
#    driver: bridge
