# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Transcendance CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build frontend
      run : docker-compose build frontend

    - name: build db
      run : docker-compose build postgres adminer

    - name: build backend
      run : docker-compose build backend
      
    - name: docker-compose up
      run: docker-compose up &

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v17.2.0
        cache: 'npm'

    - run: npm test
